---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
- name: token_tools_airdrop_start
  type: text
  config:
    required: false
  label: Token Tools
- name: airdrop_erc-20_tokens_in_a_single_transaction
  type: text
  config:
    required: false
  label: Airdrop ERC-20 Tokens in a single transaction
- name: chain
  type: select
  default: []
  config:
    required: false
    options:
    - Binance Chain
    - Huobi Chain
    - Polygon Chain
    - Fantom Chain
    - Ropsten Testnet Chain
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Chain
- name: token_address__contract_
  type: text
  config:
    required: false
  label: Token Address (Contract)
pages:
- projects/ios-concept.md
- projects/sunk.md
